### ISSUE TITLE
Won't compile on aarch64 because of cargon crate.

### ISSUE THREAD

**Issue by bentwire** [Racum/rust-djangohashers#11]
Love this library, does exactly what I need.  However I am now porting my app to aarch64 and I can't get the library to compile.  I tried disabling cargon by using the below dependency config but it still tries to compile cargon:

```
[dependencies.djangohashers]
version = "1.0.1"
features = ["fpbkdf2"]
```

Here is the cargon error:
```
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-I" "phc-winner-argon2/include" "-march=native" "-Wall" "-Wextra" "-o" "/home/android/galileo-client/target/release/build/cargon-77514a8c699451ee/out/phc-winner-argon2/src/opt.o" "-c" "phc-winner-argon2/src/opt.c"
cargo:warning=In file included from phc-winner-argon2/src/opt.c:19:0:
cargo:warning=phc-winner-argon2/src/opt.h:18:10: fatal error: emmintrin.h: No such file or directory
cargo:warning= #include <emmintrin.h>
cargo:warning=          ^~~~~~~~~~~~~
cargo:warning=compilation terminated.
exit code: 1
```

Looks like it is trying to compile optimizations that don't apply for ARM?

Is there any quick fix I can do to make my app compile?

Thanks,
Mike

**Comment by bentwire** [comment]
Looks like I just needed to add "default-features = false" to my deps section for djangohashers.

**Comment by Racum** [comment]
If you want to try with all features now, I changed the Argon2 dependency to another one in pure-Rust, that compiles nicely on ARM.
