### ISSUE TITLE
Consider using ring

### ISSUE THREAD

**Issue by LegNeato** [Racum/rust-djangohashers#12]
OpenSSL is a pain to set up and deploy. It would be great to have ring as an option instead.

**Comment by Racum** [comment]
I agree that OpenSSL is a pain, but is a sub-dependency, required by [fastpbkdf2](https://github.com/ctz/rust-fastpbkdf2), you should ping them! ...If they add this I'll be happy to make sure `djangohashers` is compatible, and update docs and CI.

**Comment by ryanmcgrath** [comment]
It's worth noting that the author of fastpbkdf2 even suggests using ring, and there's been no new version published for some time now. This is wonderful library that would be nice to see updated to use ring, so I hope this issue could be looked at again.

https://github.com/ctz/rust-fastpbkdf2/issues/3

**Comment by Racum** [comment]
Interesting... ring has a pbkdf2 implementation inside it: https://github.com/briansmith/ring/blob/main/src/pbkdf2.rs ...I'm not sure it uses the "shortcut" used  by fastpbkdf2, but it worth a try! I could reuse the Docker setup to do a benchmark. I'll have a look this next weekend.

**Comment by Racum** [comment]
This the benchmark:

```
Hashing time: 104ms (Python 3.7.9, Django 3.1.5).
Hashing time: 130ms (Vanilla PBKDF2).
Hashing time: 65ms (Fast PBKDF2).
Hashing time: 109ms (Ring PBKDF2).
```

Ring is faster than vanilla, and virtually the same as the C implementation from Python/Django; but still not as fast as *Fast-PBKDF2*.

I think I will make ring the **new** vanilla, but keep the *Fast-PBKDF2* as an option.

**Comment by Racum** [comment]
Interesting... `ring` probably have some optimisations for ARM, this is the result in my M1 MacBook Air:

```
Hashing time: 37ms (Python 3.9.1, Django 3.1.5).
Hashing time: 22ms (Vanilla PBKDF2).             <-- already ring!
Hashing time: 14ms (Fast PBKDF2).
````

Way faster than the reference implementation in C via Python.

I'm merging this! 😄

**Comment by Racum** [comment]
Done! ...update to `1.4.0` and enjoy!

Now, try to convince `ring` maintainers to implement the *"shortcut"* algorithm:

* https://www.cryptologie.net/article/281/pbkdf2-performance-matters/
* https://www.youtube.com/watch?v=k_szwKBuNBw

**Comment by ryanmcgrath** [comment]
Meant to circle back - this is awesome! Thanks for looking into it, I know OSS is a thankless job sometimes.

I use djangohashers for a Django-esque personal framework on actix-web. Solid piece of work all around.
