### ISSUE TITLE
make_password take more than 20s

### ISSUE THREAD

**Issue by acuetoblumer** [Racum/rust-djangohashers#14]
make_password take more than 20s, i'm using actix and i'm trying to use this library but i have this problem.

**Comment by acuetoblumer** [comment]
I was running in debug mode hahaha

**Comment by Racum** [comment]
Yeap, cryptographic algorithms suffer a lot in debug mode! ...I even run my CI test with `--relase`! :) ...still, 20 seconds sounds like a lot, I'm curious: did you use with the default hasher of picked a different one?
