### ISSUE TITLE
with_argon2 is it Argon2d, Argon2i, or Argon2id?

### ISSUE THREAD

**Issue by Jieiku** [Racum/rust-djangohashers#17]
with_argon2 is it Argon2d, Argon2i, or Argon2id?

Thank You!

**Comment by simoneromano96** [comment]
If I remember correctly it is argon2i

**Comment by Jieiku** [comment]
yeah, I was not sure when I seen this: https://code.djangoproject.com/ticket/30472

apparently django had a hard coded argon2i at some point, but might be argon2id now?

**Comment by Racum** [comment]
Nice catch! ...I usually copy/translate Django's tests, but these updates on Argon2 passed bellow my radar! ...I'll fix it soon!

**Comment by Racum** [comment]
Fixed on `1.5.2`.

To clarify: 
- It now encodes as `Argon2id`, but also understands old `Argon2i` notation, same as Django.
- The decode code is the same, I just added the 2 missing segments on Django's 3.2 [related test](https://github.com/django/django/blob/b6475d7/tests/auth_tests/test_hashers.py#L532):
  - *Old hashes without version attribute*
  - *Old hashes with version attribute.*

**Comment by Jieiku** [comment]
THANK YOU!
